version: '3.1'
services:
  nomie6:
    image: ianst/nomie:latest
    restart: unless-stopped
    ports:
      - 5000:80
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:3
    restart: unless-stopped
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=YOURPASSWORD
    volumes:
      - /nfs/Data/nomie/db:/opt/couchdb/data